/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_PodSchedulingGroup = map[string]string{
	"":         "PodSchedulingGroup is the configuration",
	"metadata": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
	"spec":     "Specification of the desired behavior of the pod. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status",
	"status":   "Most recently observed status of the pod. This data may not be up to date. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status",
}

func (PodSchedulingGroup) SwaggerDoc() map[string]string {
	return map_PodSchedulingGroup
}

var map_PodSchedulingGroupList = map[string]string{
	"":         "PodSchedulingGroup is a collection of priority classes.",
	"metadata": "Standard list metadata More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
	"items":    "items is the list of PodSchedulingGroup",
}

func (PodSchedulingGroupList) SwaggerDoc() map[string]string {
	return map_PodSchedulingGroupList
}

var map_PodSchedulingGroupSpec = map[string]string{
	"selector":          "Selector is a label query over pods that should be considered together by scheduler.",
	"priorityClassName": "If specified, indicates the pod's priority. \"system-node-critical\" and \"system-cluster-critical\" are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default.",
	"priority":          "The priority value. Various system components use this field to find the priority of the QueueJob. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority.",
	"minAvailable":      "The minimal available pods to run for this QueueJob; the default value is nil.",
}

func (PodSchedulingGroupSpec) SwaggerDoc() map[string]string {
	return map_PodSchedulingGroupSpec
}

var map_PodSchedulingGroupStatus = map[string]string{
	"pending":      "The number of pending pods.",
	"running":      "The number of actively running pods.",
	"succeeded":    "The number of pods which reached phase Succeeded.",
	"failed":       "The number of pods which reached phase Failed.",
	"replicas":     "Replicas is the number of desired replicas.",
	"minAvailable": "The minimal available pods to run for this QueueJob",
}

func (PodSchedulingGroupStatus) SwaggerDoc() map[string]string {
	return map_PodSchedulingGroupStatus
}

var map_PriorityClass = map[string]string{
	"":              "PriorityClass defines mapping from a priority class name to the priority integer value. The value can be any valid integer.",
	"metadata":      "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
	"value":         "The value of this priority class. This is the actual priority that pods receive when they have the name of this class in their pod spec.",
	"globalDefault": "globalDefault specifies whether this PriorityClass should be considered as the default priority for pods that do not have any priority class. Only one PriorityClass can be marked as `globalDefault`. However, if more than one PriorityClasses exists with their `globalDefault` field set to true, the smallest value of such global default PriorityClasses will be used as the default priority.",
	"description":   "description is an arbitrary string that usually provides guidelines on when this priority class should be used.",
}

func (PriorityClass) SwaggerDoc() map[string]string {
	return map_PriorityClass
}

var map_PriorityClassList = map[string]string{
	"":         "PriorityClassList is a collection of priority classes.",
	"metadata": "Standard list metadata More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
	"items":    "items is the list of PriorityClasses",
}

func (PriorityClassList) SwaggerDoc() map[string]string {
	return map_PriorityClassList
}

// AUTO-GENERATED FUNCTIONS END HERE
