// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "k8s.io/api/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	scheduling "k8s.io/kubernetes/pkg/apis/scheduling"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_PodSchedulingGroup_To_scheduling_PodSchedulingGroup,
		Convert_scheduling_PodSchedulingGroup_To_v1alpha1_PodSchedulingGroup,
		Convert_v1alpha1_PodSchedulingGroupList_To_scheduling_PodSchedulingGroupList,
		Convert_scheduling_PodSchedulingGroupList_To_v1alpha1_PodSchedulingGroupList,
		Convert_v1alpha1_PodSchedulingGroupSpec_To_scheduling_PodSchedulingGroupSpec,
		Convert_scheduling_PodSchedulingGroupSpec_To_v1alpha1_PodSchedulingGroupSpec,
		Convert_v1alpha1_PodSchedulingGroupStatus_To_scheduling_PodSchedulingGroupStatus,
		Convert_scheduling_PodSchedulingGroupStatus_To_v1alpha1_PodSchedulingGroupStatus,
		Convert_v1alpha1_PriorityClass_To_scheduling_PriorityClass,
		Convert_scheduling_PriorityClass_To_v1alpha1_PriorityClass,
		Convert_v1alpha1_PriorityClassList_To_scheduling_PriorityClassList,
		Convert_scheduling_PriorityClassList_To_v1alpha1_PriorityClassList,
	)
}

func autoConvert_v1alpha1_PodSchedulingGroup_To_scheduling_PodSchedulingGroup(in *v1alpha1.PodSchedulingGroup, out *scheduling.PodSchedulingGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PodSchedulingGroupSpec_To_scheduling_PodSchedulingGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PodSchedulingGroupStatus_To_scheduling_PodSchedulingGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PodSchedulingGroup_To_scheduling_PodSchedulingGroup is an autogenerated conversion function.
func Convert_v1alpha1_PodSchedulingGroup_To_scheduling_PodSchedulingGroup(in *v1alpha1.PodSchedulingGroup, out *scheduling.PodSchedulingGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodSchedulingGroup_To_scheduling_PodSchedulingGroup(in, out, s)
}

func autoConvert_scheduling_PodSchedulingGroup_To_v1alpha1_PodSchedulingGroup(in *scheduling.PodSchedulingGroup, out *v1alpha1.PodSchedulingGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_scheduling_PodSchedulingGroupSpec_To_v1alpha1_PodSchedulingGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_scheduling_PodSchedulingGroupStatus_To_v1alpha1_PodSchedulingGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_scheduling_PodSchedulingGroup_To_v1alpha1_PodSchedulingGroup is an autogenerated conversion function.
func Convert_scheduling_PodSchedulingGroup_To_v1alpha1_PodSchedulingGroup(in *scheduling.PodSchedulingGroup, out *v1alpha1.PodSchedulingGroup, s conversion.Scope) error {
	return autoConvert_scheduling_PodSchedulingGroup_To_v1alpha1_PodSchedulingGroup(in, out, s)
}

func autoConvert_v1alpha1_PodSchedulingGroupList_To_scheduling_PodSchedulingGroupList(in *v1alpha1.PodSchedulingGroupList, out *scheduling.PodSchedulingGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]scheduling.PodSchedulingGroup, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_PodSchedulingGroup_To_scheduling_PodSchedulingGroup(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_PodSchedulingGroupList_To_scheduling_PodSchedulingGroupList is an autogenerated conversion function.
func Convert_v1alpha1_PodSchedulingGroupList_To_scheduling_PodSchedulingGroupList(in *v1alpha1.PodSchedulingGroupList, out *scheduling.PodSchedulingGroupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodSchedulingGroupList_To_scheduling_PodSchedulingGroupList(in, out, s)
}

func autoConvert_scheduling_PodSchedulingGroupList_To_v1alpha1_PodSchedulingGroupList(in *scheduling.PodSchedulingGroupList, out *v1alpha1.PodSchedulingGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha1.PodSchedulingGroup, len(*in))
		for i := range *in {
			if err := Convert_scheduling_PodSchedulingGroup_To_v1alpha1_PodSchedulingGroup(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_scheduling_PodSchedulingGroupList_To_v1alpha1_PodSchedulingGroupList is an autogenerated conversion function.
func Convert_scheduling_PodSchedulingGroupList_To_v1alpha1_PodSchedulingGroupList(in *scheduling.PodSchedulingGroupList, out *v1alpha1.PodSchedulingGroupList, s conversion.Scope) error {
	return autoConvert_scheduling_PodSchedulingGroupList_To_v1alpha1_PodSchedulingGroupList(in, out, s)
}

func autoConvert_v1alpha1_PodSchedulingGroupSpec_To_scheduling_PodSchedulingGroupSpec(in *v1alpha1.PodSchedulingGroupSpec, out *scheduling.PodSchedulingGroupSpec, s conversion.Scope) error {
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.PriorityClassName = in.PriorityClassName
	out.Priority = (*int32)(unsafe.Pointer(in.Priority))
	out.MinAvailable = (*int32)(unsafe.Pointer(in.MinAvailable))
	return nil
}

func autoConvert_scheduling_PodSchedulingGroupSpec_To_v1alpha1_PodSchedulingGroupSpec(in *scheduling.PodSchedulingGroupSpec, out *v1alpha1.PodSchedulingGroupSpec, s conversion.Scope) error {
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.PriorityClassName = in.PriorityClassName
	out.Priority = (*int32)(unsafe.Pointer(in.Priority))
	out.MinAvailable = (*int32)(unsafe.Pointer(in.MinAvailable))
	return nil
}

// Convert_scheduling_PodSchedulingGroupSpec_To_v1alpha1_PodSchedulingGroupSpec is an autogenerated conversion function.
func Convert_scheduling_PodSchedulingGroupSpec_To_v1alpha1_PodSchedulingGroupSpec(in *scheduling.PodSchedulingGroupSpec, out *v1alpha1.PodSchedulingGroupSpec, s conversion.Scope) error {
	return autoConvert_scheduling_PodSchedulingGroupSpec_To_v1alpha1_PodSchedulingGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_PodSchedulingGroupStatus_To_scheduling_PodSchedulingGroupStatus(in *v1alpha1.PodSchedulingGroupStatus, out *scheduling.PodSchedulingGroupStatus, s conversion.Scope) error {
	out.Pending = in.Pending
	out.Running = in.Running
	out.Succeeded = in.Succeeded
	out.Failed = in.Failed
	out.Replicas = in.Replicas
	out.MinAvailable = in.MinAvailable
	return nil
}

// Convert_v1alpha1_PodSchedulingGroupStatus_To_scheduling_PodSchedulingGroupStatus is an autogenerated conversion function.
func Convert_v1alpha1_PodSchedulingGroupStatus_To_scheduling_PodSchedulingGroupStatus(in *v1alpha1.PodSchedulingGroupStatus, out *scheduling.PodSchedulingGroupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodSchedulingGroupStatus_To_scheduling_PodSchedulingGroupStatus(in, out, s)
}

func autoConvert_scheduling_PodSchedulingGroupStatus_To_v1alpha1_PodSchedulingGroupStatus(in *scheduling.PodSchedulingGroupStatus, out *v1alpha1.PodSchedulingGroupStatus, s conversion.Scope) error {
	out.Pending = in.Pending
	out.Running = in.Running
	out.Succeeded = in.Succeeded
	out.Failed = in.Failed
	out.Replicas = in.Replicas
	out.MinAvailable = in.MinAvailable
	return nil
}

// Convert_scheduling_PodSchedulingGroupStatus_To_v1alpha1_PodSchedulingGroupStatus is an autogenerated conversion function.
func Convert_scheduling_PodSchedulingGroupStatus_To_v1alpha1_PodSchedulingGroupStatus(in *scheduling.PodSchedulingGroupStatus, out *v1alpha1.PodSchedulingGroupStatus, s conversion.Scope) error {
	return autoConvert_scheduling_PodSchedulingGroupStatus_To_v1alpha1_PodSchedulingGroupStatus(in, out, s)
}

func autoConvert_v1alpha1_PriorityClass_To_scheduling_PriorityClass(in *v1alpha1.PriorityClass, out *scheduling.PriorityClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Value = in.Value
	out.GlobalDefault = in.GlobalDefault
	out.Description = in.Description
	return nil
}

// Convert_v1alpha1_PriorityClass_To_scheduling_PriorityClass is an autogenerated conversion function.
func Convert_v1alpha1_PriorityClass_To_scheduling_PriorityClass(in *v1alpha1.PriorityClass, out *scheduling.PriorityClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_PriorityClass_To_scheduling_PriorityClass(in, out, s)
}

func autoConvert_scheduling_PriorityClass_To_v1alpha1_PriorityClass(in *scheduling.PriorityClass, out *v1alpha1.PriorityClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Value = in.Value
	out.GlobalDefault = in.GlobalDefault
	out.Description = in.Description
	return nil
}

// Convert_scheduling_PriorityClass_To_v1alpha1_PriorityClass is an autogenerated conversion function.
func Convert_scheduling_PriorityClass_To_v1alpha1_PriorityClass(in *scheduling.PriorityClass, out *v1alpha1.PriorityClass, s conversion.Scope) error {
	return autoConvert_scheduling_PriorityClass_To_v1alpha1_PriorityClass(in, out, s)
}

func autoConvert_v1alpha1_PriorityClassList_To_scheduling_PriorityClassList(in *v1alpha1.PriorityClassList, out *scheduling.PriorityClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]scheduling.PriorityClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PriorityClassList_To_scheduling_PriorityClassList is an autogenerated conversion function.
func Convert_v1alpha1_PriorityClassList_To_scheduling_PriorityClassList(in *v1alpha1.PriorityClassList, out *scheduling.PriorityClassList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PriorityClassList_To_scheduling_PriorityClassList(in, out, s)
}

func autoConvert_scheduling_PriorityClassList_To_v1alpha1_PriorityClassList(in *scheduling.PriorityClassList, out *v1alpha1.PriorityClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.PriorityClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_scheduling_PriorityClassList_To_v1alpha1_PriorityClassList is an autogenerated conversion function.
func Convert_scheduling_PriorityClassList_To_v1alpha1_PriorityClassList(in *scheduling.PriorityClassList, out *v1alpha1.PriorityClassList, s conversion.Scope) error {
	return autoConvert_scheduling_PriorityClassList_To_v1alpha1_PriorityClassList(in, out, s)
}
